name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build QuickJS Static Library
    strategy:
        fail-fast: false
        matrix:
            platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
          submodules: true
          fetch-depth: 1

    - name: Prebuild for linux
      if: matrix.platform == 'ubuntu-latest'
      run: rm -rf deps/libs/linux* && docker pull multiarch/crossbuild
    
    - name: Build linux amd64
      if: matrix.platform == 'ubuntu-latest'
      run: mkdir -p deps/libs/linux_amd64 && cd deps/quickjs && docker run --rm -v $(pwd):/workdir multiarch/crossbuild /bin/bash -c "cd /workdir && make clean && make -e CONFIG_LTO=y libquickjs.a "  && mv libquickjs.a ../libs/linux_amd64

    - name: Build linux arm64
      if: matrix.platform == 'ubuntu-latest'
      run: mkdir -p deps/libs/linux_arm64 && cd deps/quickjs && docker run --rm -v $(pwd):/workdir -e CROSS_TRIPLE=aarch64-linux-gnu multiarch/crossbuild /bin/bash -c "cd /workdir && make clean && make -e CONFIG_LTO=y libquickjs.a "  && mv libquickjs.a ../libs/linux_arm64

    - name: Create PR For Linux 
      if: matrix.platform == 'ubuntu-latest'
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update QuickJS Static Library For Linux
        branch-suffix: random
        delete-branch: true
        title: Update QuickJS Static library For Linux
      
    - name: Prebuild for mac
      if: matrix.platform == 'macos-latest'
      run: rm -rf deps/libs/darwin_* && cp -a deps/Makefile deps/quickjs

    - name: Build darwin amd64 
      if: matrix.platform == 'macos-latest'
      run: mkdir -p deps/libs/darwin_amd64 && cd deps/quickjs && make clean && make -e CONFIG_CLANG=y CONFIG_DEFAULT_AR=y CONFIG_LTO=y libquickjs.a && mv libquickjs.a ../libs/darwin_amd64

    - name: Build darwin arm64 
      if: matrix.platform == 'macos-latest'
      run: mkdir -p deps/libs/darwin_arm64 && cd deps/quickjs && make clean && make -e CONFIG_CLANG=y CONFIG_DEFAULT_AR=y CONFIG_DARWIN_ARM64=y CONFIG_LTO=y libquickjs.a && mv libquickjs.a ../libs/darwin_arm64
      
    - name: Create PR For Darwin
      if: matrix.platform == 'macos-latest'
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update QuickJS Static Library For Darwin
        branch-suffix: random
        delete-branch: true
        title: Update QuickJS Static library For Darwin

    - name: Prebuild for windows
      if: matrix.platform == 'windows-latest'
      run: copy deps/Makefile deps/quickjs

    - name: Build windows amd64 
      if: matrix.platform == 'windows-latest'
      run: cd deps/quickjs && make clean && make -e CONFIG_WIN32=y CONFIG_LTO=y libquickjs.a && copy libquickjs.a ../libs/windows_amd64

    - name: Create PR For Windows
      if: matrix.platform == 'windows-latest'
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update QuickJS Static Library For Windows
        branch-suffix: random
        delete-branch: true
        title: Update QuickJS Static library For Windows
